name = "sealife-api"
main = "src/index.ts"
compatibility_date = "2025-08-31"


[observability]
enabled = true


# Bind D1 later, example:
#[[d1_databases]]
#binding = "DB"
#database_name = "sealife-d1"
#database_id = "REPLACE_ME"